Places first name and last name on the same line to prevent trimming of the space between them
CuBoulder/tiamat-theme pull request #1328
Opened 2024-09-24 17:00 UTC by timurtripp

[bug] An issue existed where a space was trimmed between the first name and last name on person pages due to the names being separated by a newline. This update resolves the issue. Resolves CuBoulder/tiamat-theme#1304

2024-09-24 17:07 UTC, timurtripp commented
The two template deletions are simply due to them becoming dead code since I'm referencing the value directly.

2024-09-24 21:12 UTC, jcsparks requested changes

2024-09-24 21:12 UTC, jcsparks commented on templates/content/node--ucb-person.html.twig
> +      <span itemprop="givenName">{{ content.field_ucb_person_first_name.0 }}</span> <span itemprop="familyName">{{ content.field_ucb_person_last_name.0 }}</span>
We lost the`|trim` on the first and last name content, that's probably still useful to correct simple user-entered data errors.  

We don't have good visibility or control over the Fastly optimization and given that this is already behaving differently with different browsers I want to have a real solution that we can rely on that's under out control.  Please change the whitespace character to an HTML non-breaking space.

2024-09-25 16:47 UTC, jcsparks approved these changes

2024-09-25 16:47 UTC, merged