Issue/1435
CuBoulder/tiamat-theme pull request #1456
Opened 2024-11-10 23:28 UTC by jnicholCU

Handful of updates for the above and below content regions as well as the homepage footer style

Sister PR: 

Resolves #1435

2024-11-11 00:41 UTC, jnicholCU commented
Header and Footer options are in the Advanced section of `/admin/config/cu-boulder/appearance`

2024-11-12 17:58 UTC, jcsparks requested changes
Is there a a way to make the social media links part of the footer?  

<img width="1135" alt="Screenshot 2024-11-12 at 10 56 37 AM" src="https://github.com/user-attachments/assets/ffbe6430-6a1f-4a31-ae20-6153c4806ce1">

2024-11-12 21:53 UTC, jnicholCU commented
For the social media menu if you move it into the `Site Information` region it should show up now as expected. Good catch I missed adding that in how Kevin suggested. You can also disable the `Site Contact Info Footer` as that won't be necessary on the homepage.

<img width="336" alt="image" src="https://github.com/user-attachments/assets/4a47ec00-30e8-467e-a6bc-99b83cc56cee">

2024-11-12 23:36 UTC, jcsparks approved these changes

2024-11-12 23:36 UTC, merged