User and 404 page changes
CuBoulder/tiamat-theme pull request #493
Opened 2023-09-28 17:43 UTC by jacob-korf

Closes #484.
Adds the new implementation of the user page and stores the image for the 404 page.

2023-09-28 19:44 UTC, patrickbrown-io reviewed
New User page looks really good! Installs without issue and the status block element works well. That and documentation really adds some value to the user page.

My only suggestion is adding a little more padding to the top of the main content, maybe 10px to mirror the bottom padding? Right now it looks like its pressed up against that top menu bar. But other than that little style change I think its good to go! Nice work!

<img width="922" alt="Screenshot 2023-09-28 at 1 32 48 PM" src="https://github.com/CuBoulder/tiamat-theme/assets/85851903/e6db2381-4c14-435e-b5d3-f4ff3c2c416a">

2023-09-28 19:51 UTC, jacob-korf commented
Sounds good, that problem should be fixed now!

2023-09-28 19:52 UTC, patrickbrown-io approved these changes

2023-10-09 20:44 UTC, timurtripp requested changes
The only change I request is to increase the `padding-top` from `10px` to `20px`. After that I will approve it!

2023-10-10 16:42 UTC, timurtripp approved these changes

2023-10-10 18:17 UTC, merged