image gallery bug fix
CuBoulder/tiamat-theme pull request #655
Opened 2024-02-09 20:26 UTC by jacob-korf

Closes #642.
Quick fix to make image gallery work.

2024-02-13 17:47 UTC, jacob-korf commented
Closes #656 as well.

2024-02-15 15:46 UTC, jcsparks commented on templates/block/block--image-gallery.html.twig
> +					<a href="{{ file_url(item.entity.field_media_image.entity.fileuri) }}" class="glightbox ucb-gallery-lightbox" data-gallery="gallery{{ content['#block_content'].id() }}" data-glightbox="descripti
What is this?   Surely the description shouldn't be a hard-coded string to "yup"

2024-02-15 15:48 UTC, jcsparks requested changes
It's okay to have a default value for the description if that's required but something more commonly applicable like "Image" is probably appropriate.  If we have a real description it should use that.

2024-02-15 16:52 UTC, jcsparks approved these changes

2024-02-15 16:52 UTC, merged